### ISSUE TITLE
Added a setting to control maxplaysday

### ISSUE THREAD

**Issue by Kavex** [PaulBender/My-Arcade#11]
So like title say a settings to change the max plays a day would be grand My members were complaining to me about the max games so i looked at the settings and i didn't see anything. I saw it was adding it to the DB. $db->add_column("usergroups", "maxplaysday", "int NOT NULL default '25'");

is there a setting an i'm missing it?

**Comment by Starpaul20** [comment]
It's in the usergroup settings.

**Comment by Kavex** [comment]
idk how i missed this, thanks
