### ISSUE TITLE
Converting from Game Section

### ISSUE THREAD

**Issue by paretje** [PaulBender/My-Arcade#3]
I'm the developer of the "Game Section" plugin, which I've written now 10 years ago. As I'm no longer really using it myself, and as it's not exactly an example of good coding, supporting a new MyBB version would definitely require a complete rewrite. I will continue to provide fixes if needed for the current version, but I'm not going to support MyBB 2.0 when (or if?) it's released.

Will My Arcade support a future MyBB version? Is there currently a script to convert an existing Game Section database to My Arcade?

**Comment by Starpaul20** [comment]
Yes, I will support My Arcade for future versions of MyBB. A converter script can be found here: https://community.mybb.com/thread-167727-post-1143633.html#pid1143633

**Comment by paretje** [comment]
Thanks. When MyBB 2.0 is released, I'll redirect users to My Arcade.
